# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eeb6b0f159c5d40d676169195dab25c89d2313231e3fd988576690117c69d7bb8fdd4c4a49721165c3eafa6a3b283f7e353c4c819622ef7d6c0559b366fb123

test:
  secret_key_base: ae0c7f5859188788748e7da0d2bc396c9ef9c25d096c1a3c3be660360311d05574d497433b66d9aa2a91c9838caab878e05618a2104cbf901c500533cbfbc42f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
